mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mofan.xhs.domain

spring:
  datasource:
    url: jdbc:sqlite:E:/xhs/xhs.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

logging:
  path: E:/xhs/logs
server:
  port: 80

