mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mofan.xhs.domain

spring:
  datasource:
    url: jdbc:sqlite:C:/Users/poppy/IdeaProjects/xhs/xhs/src/main/resources/xhs.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

